name: Birthday Discord Bot

on:
  schedule:
    # Runs at 00:00 Melbourne time (AEST/AEDT, UTC+10/11). Use 13:00 UTC for 00:00 AEST, 13:00 UTC for 00:00 AEDT (DST not handled, but 13:00 UTC is midnight for both).
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-birthday-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run birthday bot
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HR_DISCORD_ID: ${{ secrets.HR_DISCORD_ID }}
        run: python main.py